package com.example.feelslike.utilities


// This Map contains several common activity levels and their corresponding met values
val activityMap = mapOf<String, Double>(
    "Sleeping" to 0.7,
    "Reclining" to 0.8,
    "Seated, quiet" to 1.0,
    "Reading, seated" to 1.0,
    "Writing" to 1.0,
    "Typing" to 1.1,
    "Standing, relaxed" to 1.2,
    "Filing, seated" to 1.2,
    "Filing, standing" to 1.4,
    "Flying aircraft, routine" to 1.2,
    "Driving a car" to 1.5,
    "Walking about" to 1.7,
    "Cooking" to 1.8,
    "Table sawing" to 1.8,
    "Walking 2mph (3.2kmh)" to 2.0,
    "Lifting/packing" to 2.1,
    "Seated, heavy limb movement" to 2.2,
    "Light machine work" to 2.2,
    "Flying aircraft, combat" to 2.4,
    "Walking 3mph (4.8kmh)" to 2.6,
    "House cleaning" to 2.7,
    "Driving, heavy vehicle" to 3.2,
    "Dancing" to 3.4,
    "Calisthenics" to 3.5,
    "Walking 4mph (6.4kmh)" to 3.8,
    "Tennis" to 3.8,
    "Heavy machine work" to 4.0,
    "Handling 100lb (45 kg) bags" to 4.0,
    "Pick and shovel work" to 4.4,
    "Basketball" to 6.3,
    "Wrestling" to 7.8
)

// This Map contains the total clothing insulation of typical ensembles
val clothingEnsembleMap = mapOf<String, Double>(
    "Walking shorts, short-sleeve shirt" to 0.36,
    "Typical summer indoor clothing" to 0.5,
    "Knee-length skirt, short-sleeve shirt, sandals, underwear" to 0.54,
    "Trousers, short-sleeve shirt, socks, shoes, underwear" to 0.57,
    "Trousers, long-sleeve shirt" to 0.61,
    "Knee-length skirt, long-sleeve shirt, full slip" to 0.67,
    "Sweat pants, long-sleeve sweatshirt" to 0.74,
    "Jacket, Trousers, long-sleeve shirt" to 0.96,
    "Typical winter indoor clothing" to 1.0,
)

// This Map contains the clothing values of individual clothing elements. To calculate
// the total clothing insulation, add the values together.

val clothingIndividualGarments = mapOf<String, Double>(
    "Metal chair" to 0.00,
    "Bra" to 0.01,
    "Wooden stool" to 0.01,
    "Ankle socks" to 0.02,
    "Shoes or sandals" to 0.02,
    "Slippers" to 0.03,
    "Panty hose" to 0.02,
    "Calf length socks" to 0.03,
    "Women's underwear" to 0.03,
    "Men's underwear" to 0.04,
    "Knee socks (thick)" to 0.06,
    "Short shorts" to 0.06,
    "Walking shorts" to 0.08,
    "T-shirt" to 0.08,
    "Standard office chair" to 0.10,
    "Executive chair" to 0.15,
    "Boots" to 0.1,
    "Sleeveless scoop-neck blouse" to 0.12,
    "Half slip" to 0.14,
    "Long underwear bottoms" to 0.15,
    "Full slip" to 0.16,
    "Short-sleeve knit shirt" to 0.17,
    "Sleeveless vest (thin)" to 0.1,
    "Sleeveless vest (thick)" to 0.17,
    "Sleeveless short gown (thin)" to 0.18,
    "Short-sleeve dress shirt" to 0.19,
    "Sleeveless long gown (thin)" to 0.2,
    "Long underwear top" to 0.2,
    "Thick skirt" to 0.23,
    "Long-sleeve dress shirt" to 0.25,
    "Long-sleeve flannel shirt" to 0.34,
    "Long-sleeve sweat shirt" to 0.34,
    "Short-sleeve hospital gown" to 0.31,
    "Short-sleeve short robe (thin)" to 0.34,
    "Short-sleeve pajamas" to 0.42,
    "Long-sleeve long gown" to 0.46,
    "Long-sleeve short wrap robe (thick)" to 0.48,
    "Long-sleeve pajamas (thick)" to 0.57,
    "Long-sleeve long wrap robe (thick)" to 0.69,
    "Thin trousers" to 0.15,
    "Thick trousers" to 0.24,
    "Sweatpants" to 0.28,
    "Overalls" to 0.30,
    "Coveralls" to 0.49,
    "Thin skirt" to 0.14,
    "Long-sleeve shirt dress (thin)" to 0.33,
    "Long-sleeve shirt dress (thick)" to 0.47,
    "Short-sleeve shirt dress" to 0.29,
    "Sleeveless, scoop-neck shirt (thin)" to 0.23,
    "Sleeveless, scoop-neck shirt (thick)" to 0.27,
    "Long sleeve shirt (thin)" to 0.25,
    "Long sleeve shirt (thick)" to 0.36,
    "Single-breasted coat (thin)" to 0.36,
    "Single-breasted coat (thick)" to 0.44,
    "Double-breasted coat (thin)" to 0.42,
    "Double-breasted coat (thick)" to 0.48,
)